/**
 * ObsidianWriter.ts - Save responses as Obsidian-compatible Markdown
 *
 * Saves to ~/.claude/scratchpad/telegram-saves/
 * User can symlink this folder to their Obsidian vault
 */

import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';

// ============================================================================
// Configuration
// ============================================================================

const PAI_DIR = process.env.PAI_DIR || join(process.env.HOME!, '.claude');
const DEFAULT_SAVES_PATH = join(PAI_DIR, 'scratchpad/telegram-saves');

// ============================================================================
// Types
// ============================================================================

export interface SaveMetadata {
  type: 'chat' | 'research' | 'fabric';
  userQuery: string;
  topic?: string;
  pattern?: string;
  tags?: string[];
}

export interface SaveResult {
  success: boolean;
  filePath?: string;
  error?: string;
}

// ============================================================================
// ObsidianWriter Class
// ============================================================================

export class ObsidianWriter {
  private savesPath: string;

  constructor() {
    this.savesPath = process.env.TELEGRAM_SAVES_PATH || DEFAULT_SAVES_PATH;
    this.ensureDirectory();
  }

  /**
   * Ensure the saves directory exists
   */
  private ensureDirectory(): void {
    if (!existsSync(this.savesPath)) {
      mkdirSync(this.savesPath, { recursive: true });
    }
  }

  /**
   * Generate a filename from metadata
   */
  private generateFilename(metadata: SaveMetadata): string {
    const now = new Date();

    // Format: YYYY-MM-DD_HHMMSS_type_topic.md
    const date = now.toISOString().split('T')[0];
    const time = now.toTimeString().split(' ')[0].replace(/:/g, '');

    // Sanitize topic for filename
    let topic = metadata.topic || metadata.pattern || 'response';
    topic = topic
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50);

    return `${date}_${time}_${metadata.type}_${topic}.md`;
  }

  /**
   * Generate YAML frontmatter
   */
  private generateFrontmatter(metadata: SaveMetadata, timestamp: Date): string {
    const lines: string[] = ['---'];

    lines.push(`created: ${timestamp.toISOString()}`);
    lines.push(`source: telegram-bot`);
    lines.push(`type: ${metadata.type}`);

    if (metadata.pattern) {
      lines.push(`pattern: ${metadata.pattern}`);
    }

    if (metadata.topic) {
      lines.push(`topic: "${metadata.topic.replace(/"/g, '\\"')}"`);
    }

    // Generate tags
    const tags = ['pai', 'telegram', metadata.type];
    if (metadata.pattern) tags.push(metadata.pattern);
    if (metadata.tags) tags.push(...metadata.tags);
    lines.push(`tags: [${tags.join(', ')}]`);

    lines.push('---');
    return lines.join('\n');
  }

  /**
   * Generate the document title based on metadata
   */
  private generateTitle(metadata: SaveMetadata): string {
    switch (metadata.type) {
      case 'research':
        return `Research: ${metadata.topic || 'Unknown Topic'}`;
      case 'fabric':
        return `${metadata.pattern || 'Fabric'}: Analysis`;
      case 'chat':
      default:
        return `Chat: ${this.extractTitle(metadata.userQuery)}`;
    }
  }

  /**
   * Extract a title from user query (first line or first 50 chars)
   */
  private extractTitle(query: string): string {
    const firstLine = query.split('\n')[0];
    if (firstLine.length <= 60) {
      return firstLine;
    }
    return firstLine.substring(0, 57) + '...';
  }

  /**
   * Save content to a Markdown file
   */
  async save(content: string, metadata: SaveMetadata): Promise<SaveResult> {
    try {
      this.ensureDirectory();

      const timestamp = new Date();
      const filename = this.generateFilename(metadata);
      const filePath = join(this.savesPath, filename);

      // Build the full document
      const frontmatter = this.generateFrontmatter(metadata, timestamp);
      const title = this.generateTitle(metadata);

      let document = frontmatter;
      document += '\n\n';
      document += `# ${title}\n\n`;

      // Add query section
      if (metadata.userQuery) {
        document += `## Query\n\n`;
        document += `> ${metadata.userQuery.split('\n').join('\n> ')}\n\n`;
      }

      // Add main content
      document += `## Response\n\n`;
      document += content;
      document += '\n\n';

      // Add footer
      document += '---\n';
      document += `*Generated by PAI via Telegram on ${timestamp.toISOString().split('T')[0]}*\n`;

      // Write the file
      await Bun.write(filePath, document);

      return {
        success: true,
        filePath,
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Get the saves directory path
   */
  getSavesPath(): string {
    return this.savesPath;
  }

  /**
   * List recent saves
   */
  async listRecent(limit: number = 10): Promise<string[]> {
    if (!existsSync(this.savesPath)) {
      return [];
    }

    try {
      const { readdirSync, statSync } = await import('fs');

      const files = readdirSync(this.savesPath)
        .filter((f) => f.endsWith('.md'))
        .map((f) => ({
          name: f,
          mtime: statSync(join(this.savesPath, f)).mtime,
        }))
        .sort((a, b) => b.mtime.getTime() - a.mtime.getTime())
        .slice(0, limit)
        .map((f) => f.name);

      return files;
    } catch {
      return [];
    }
  }
}

export default ObsidianWriter;
